# Page settings

baseURL = "https://huyphan5677.github.io/huyphan-cv/"
languageCode = "en"
title = "HuyPhan's Résumé"
theme = "hugo-devresume-theme"
publishDir = "docs"





[params]
    author = "Huyphan"
    description = "Huyphan's Résumé"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Phan Minh Huy"
        tagline = "Data Scientist"
        avatar = "Asset 2.png"







    [params.contact]
        enable = true
        location = "District 4, HCMC"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0356 046 970"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "huyphan5677@gmail.com"








    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Hard skills"
        [[params.skills.list.items]]
        details = "Coding skills: Python, R, SQL"
        [[params.skills.list.items]]
        details = "Statistics softwares: Alteryx, SPSS"
        [[params.skills.list.items]]
        details = "Machine learning algorithms"
        [[params.skills.list.items]]
        details = "ETL data with Pyspark"

        [[params.skills.list]]
        title = "Soft skills"
        [[params.skills.list.items]]
        details = "TOEIC test: 665/990"
        [[params.skills.list.items]]
        details = "Problem-solving"
        [[params.skills.list.items]]
        details = "Willing to listen or to consider new ideas"
        [[params.skills.list.items]]
        details = "Hard-working under high pressure"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Data Science"
        university = "Ho Chi Minh University of Science"
        dates = "12/2020 - Now"
        edu_describe = "Knowledge: Machine Learning & Deep Learning algorithms"

        [[params.education.list]]
        degree = "Bachelor of Industrial System Engineering"
        university = "Ho Chi Minh City University of Technology"
        dates = "08/2015 - 11/2019"
        GPA = "GPA: 8.4/10"
        edu_describe = "Knowledge: Supply Chain management and optimization"




    [params.summary]
        enable = true
        text = "I am a Data Scientist committed to using detailed analysis and creative approaches to solve problems across various industries. My approach blends advanced data analytics and machine learning to streamline workflows and uncover valuable insights. With these techniques, I effectively drive improvements and strategic changes in complex business environments."



    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Data Scientist"
        company = "Prudential VietNam Assurance | 11/2022 – 08/2024"
        details1 = "1. General Responsibilities"
        details2 = "2. Modeling projects"


        [[params.experience.list.items1]]
        details1 = "Performing end-to-end data science project tasks, including data cleaning, feature engineering, model development, and performance evaluation aligned with business objectives."
        [[params.experience.list.items1]]
        details1 = "Conducted training sessions for teams and departments to leverage advanced technologies, fostering a culture of continuous learning within the department."

        [[params.experience.list.items2]]
        details2 = "Predicting potential customers for cross-selling insurance policies."
        [[params.experience.list.items2]]
        details2 = "Predicting the probability of claim rejection, automating the decision-making process."
        [[params.experience.list.items2]]
        details2 = "Applying a clustering model to identify high-quality leader profiles based on insightful data analysis and building an early prediction model to identify potential leaders among agents."
        [[params.experience.list.items2]]
        details2 = "Building a model to predict lapsing customers, determining whether they will pay insurance premiums (churn prediction)."
        
        [[params.experience.list.items2]]
        details2 = "Keywords: Classification problems, Clustering, SHAP analysis, Conformal prediction, Graph analysis."


        [[params.experience.list]]
        title = "Data Analyst/Data Scientist"
        company = "CIC Data Jsc | 08/2020 – 06/2022"
        details1 = "1. Modeling projects"
        details2 = "2. Operations"

        [[params.experience.list.items1]]
        details1 = "Extracting dense communities from Call Center and SMS Center Graphs to valuable features using graphframes, DBScan, KMeans."
        [[params.experience.list.items1]]
        details1 = "Building models of propensity scores with production performance 64% and 70% Gini, respectively."
        [[params.experience.list.items1]]
        details1 = "Building a model to predict the probabilities of LeadGen Filtering problem (used to optimize the revenue/SMS)."
        [[params.experience.list.items1]]
        details1 = "Proposing and monitoring the A/B testing plans on models."
        [[params.experience.list.items1]]
        details1 = "Using Ortools to solve optimization problems in LeadGen selection to maximize revenue and reduce operation costs."
        [[params.experience.list.items1]]
        details1 = "Keywords: Classification problems, Graph analysis, Clustering, ETL & Data mining using Spark."
        
        [[params.experience.list.items2]]
        details2 = "Operating & monitoring & Standardizing Mortgage LeadGen service at telcos, ensuring the service is stable and meet all terms."
        [[params.experience.list.items2]]
        details2 = "Providing ad-hoc analysis to get actionable insights and to optimize revenue."


        [[params.experience.list]]
        title = "Machine Learning Engineer"
        company = "SIFT AG VN | 10/2018 – 07/2020"
        details1 = "Project"

        [[params.experience.list.items1]]
        details1 = "PCVFC: Forecasting fertilizer prices for products at different areas in the world; forecasting fertilizer demand and forecasting fertilizer price-demand in Vietnam (Full SOW in Crisp-DM methodology)."
        [[params.experience.list.items1]]
        details1 = "PNJ: Solve Market Basket Analysis, Store Clustering and Store Performance problems."
        [[params.experience.list.items1]]
        details1 = "DFS: Creating predictive models to forecast sum sales based on both internal and external data. Developing an Automated ML pipeline runs monthly with Alteryx Platform (Full SOW in Crisp-DM methodology)."
        [[params.experience.list.items1]]
        details1 = "Keywords: TimeSeries forecasting, Regression, Market Basket Analysis, Clustering."


[params.information]
        enable = true

        [[params.information.list]]
        title = "Ms. Trang Nguyen"
        [[params.information.list.items]]
        details = "Former Head of Data at CIC Data Jsc"
        [[params.information.list.items]]
        details = "nguyentranguf@gmail.com"

        [[params.information.list]]
        title = "Mr. Trung Bui Quoc"
        [[params.information.list.items]]
        details = "Lecturer at Hanoi University of Science"
        [[params.information.list.items]]
        details = "trungbq@soict.hust.edu.vn"




    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/huy-phan-270014111/"
        title = "Huy Phan"






